### ISSUE TITLE
Implement in-place snapshot generation

### ISSUE THREAD

**Issue by ashwinphatak** [cerc-io/ipld-eth-state-snapshot#38]
Support creating snapshots from an earlier snapshot + statediffs. 

Ian has already pointed out a potential in-place snapshot generation approach here: https://github.com/vulcanize/ops/issues/137#issuecomment-1064736933 and an initial impl here: https://github.com/vulcanize/ipld-eth-db/pull/56/files#diff-e582d50b7d12508c81e2e7b700e9b86841731b883fdcfe044ba5a9951d376e03

CLI subcommands to implement
- [x] Trie based snapshot
- [ ] In-place snapshot
  - [x] Command to take in-place snapshot
  - [ ] Combine state and storage snapshot functions into a single procedure
  - [ ] Check implications of contract/storage slot destruction
  - [ ] Add negative tests for [orphaned/non-canonical](https://github.com/vulcanize/ipld-eth-db/pull/56#issue-1184106178) statediff payloads

**Comment by prathamesh0** [comment]
* Currently, in-place snapshot generation functions don't index IPFS `blocks` for contract code like it's done in trie based snapshot.
* eth-calls served using the indexed data (by `ipld-eth-server` for example) use contract code from the respective IPFS `blocks`. Since in-place snapshot currently only indexes state and storage nodes, eth-calls might fetch data outside the in-place snapshot bounds for contracts whose code nodes are indexed at a lower height.
* This behaviour needs discussion as the in-place snapshots are not self-sufficient for all operations in the corresponding block range.

**Comment by nikugogoi** [comment]
For orphaned/non-canonical statediff payloads:
* Currently, in-place snapshot will also process non canonical blocks in the snapshot range. Need to create snapshot using only blocks in canonical chain.
  * Proposed solution: Use canonical header function while taking in-place snapshot to avoid non canonical data from forks.            
* Snapshot will be incorrect if canonical blocks are missing in the snapshot range.
  * Implement CTE query for checking that all canonical headers exist in snapshot range.
  * To avoid forks (due to missing children in data) in the snapshot range (especially towards the `ending_height`), need to check headers beyond end height (max +16) to ensure canonicity.
  `canonical_header_hash` function is used to get the canonical block at snapshot `ending_height`. If there are missing children in canonical chain after `ending_height`, it might return non-canonical block.

**Comment by i-norden** [comment]
We will need to rethink this for v5, since we no longer index intermediate trie nodes

**Comment by AFDudley** [comment]
This should remain open until we have a working solution for v5, thanks.

**Comment by i-norden** [comment]
Got it, my thinking was that this issue is focused on a particular implementation (the one linked to in the OP) and this implementation is not possible in v5 and so most of the discussion here is noise and none of the remaining checkboxes can be ticked.

**Comment by AFDudley** [comment]
Yeah, your thinking makes sense, I should have asked for clarification instead of re-opening the issue.
